version: '3'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.28
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment: 
      - MYSQL_ROOT_PASSWORD=password  
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
    networks:   
      - network-zabbix

  zabbix-server:
    container_name: zabbix-server 
    image: zabbix/zabbix-server-mysql:ubuntu-6.0.3
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=zabbix
    networks:
      - network-zabbix
    depends_on:
      - mysql

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-6.0.3
    ports:
      - '8080:8080'
      - '443:443'
    environment:
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=America/Sao_Paulo  # Corrected variable name
      - ZBX_SERVER_HOST=zabbix-server
    networks:   
      - network-zabbix
    depends_on:
      - mysql

